### ISSUE TITLE
Expand finds no tab for formatting

### ISSUE THREAD

**Issue by aggsol** [jeffsp/makefile_help#1]
my help output has no tabs, so the `expand` call did nothing for me. I had to add a `\t` like this:

```Makefile
@grep '^.PHONY: .* #' Makefile | sed 's/\.PHONY: \(.*\) # \(.*\)/\1 \t\2/' | expand -t20
```
Is this maybe platform specific? I am using it on the current Ubuntu.

**Comment by jeffsp** [comment]
It's not platform specific. It's because the Makefile has had the tab characters stripped out for some reason.

The space in `\1 \2` is actually a tab character in the original, just as the spaces before the `@echo` commands and the `@grep` command are tabs, as required by the Makefile format.

But when I download the zipfile for this project and unzip it, the tabs in the Makefile have been converted to spaces.

I will fix it and upload a new version with spaces. Thanks for pointing this out.
